name: Gitleaks
description: Runs Gitleaks
branding:
  color: purple
  icon: eye
inputs:
  config-path:
    description: 'Path to config (relative to $GITHUB_WORKSPACE)'
    required: false
outputs:
  result: # id of output
    description: 'Gitleaks log output'
  exitcode: # id of output
    description: 'Success for failure value from scan'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.config-path }}
