name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: gitleaks custom config
      uses: bpo/gitleaks-action@master
      with:
        # Custom config ignores planted secrets early in project history
        config-path: gitleaks.toml
  gitleaks-head:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Fetch depth of 1 ignores secrets early in project history
        fetch-depth: 1
    - name: gitleaks default config
      uses: bpo/gitleaks-action@master
    - name: gitleaks no-git
      uses: bpo/gitleaks-action@master
      with:
        no-git: true
